version: '2'
services:
  web:
    image: 'registry.gitlab.com/sweetbonus/api:latest'
    container_name: api-sweet
    ports:
        - 8000:80
    environment:
        XDEBUG_CONFIG: remote_host= 172.17.0.1
    volumes:
        - ./:/var/www/html

